### ISSUE TITLE
iOS version

### ISSUE THREAD

**Issue by Emasoft** [JosefAlbers/whisper-turbo-mlx#2]
What about an iOS version? I have an iPad Pro M4, and it should be very fast on it!

**Comment by JosefAlbers** [comment]
Thanks so much for your interest! Sorry I'm not very certain at this moment about the compatibility of MLX with iOS, as it I think primarily supports macOS environments. However, I do agree with you, and I will be exploring options for running this on iOS, like porting to Swift or using frameworks that support Python.
