### ISSUE TITLE
Support for --word_timestamps

### ISSUE THREAD

**Issue by rioffe** [JosefAlbers/whisper-turbo-mlx#3]
Would it be possible to implement support for word timestamps? And output them in .json file.

So 0_test.mp3 would produce something like this:

{"text": " he broke his ties with groups of former friends.", "segments": [{"id": 0, "seek": 0, "start": 0.0, "end": 2.12, "text": " he broke his ties with groups of former friends.", "tokens": [5036    5, 415, 6902, 702, 14039, 365, 3935, 295, 5819, 1855, 13, 50484], "temperature": 0.0, "avg_logprob": -0.2811406942514273, "compression_ratio": 0.8888888888888888, "no_speech_prob": 2.7216827424604573    e-13, "words": [{"word": " he", "start": 0.0, "end": 0.16, "probability": 0.5108894109725952}, {"word": " broke", "start": 0.16, "end": 0.42, "probability": 0.9929890632629395}, {"word": " his", "sta    rt": 0.42, "end": 0.6, "probability": 0.9917784333229065}, {"word": " ties", "start": 0.6, "end": 0.88, "probability": 0.9973449110984802}, {"word": " with", "start": 0.88, "end": 1.1, "probability":     0.9941546320915222}, {"word": " groups", "start": 1.1, "end": 1.38, "probability": 0.980868399143219}, {"word": " of", "start": 1.38, "end": 1.56, "probability": 0.9978156089782715}, {"word": " form    er", "start": 1.56, "end": 1.8, "probability": 0.9916045069694519}, {"word": " friends.", "start": 1.8, "end": 2.12, "probability": 0.9920713305473328}]}], "language": "en"}

**Comment by JosefAlbers** [comment]
Something like following would do the job:

```python
    def recurrent_timestamped(self, raw, sot):
        new_tok, i = mx.zeros((1,0), dtype=mx.int32), 0
        timestamped = {} # NEW
        while i+3000 < len(raw):
            piece = self.step(raw[i:i+3000][None], sot)
            arg_hop = mx.argmax(piece).item()
            hop = (piece[:,arg_hop].astype(mx.int32).item()-50365)*2
            new_tok = mx.concatenate([new_tok, piece[:,:arg_hop]], axis=-1)
            timestamped[i/100] = self.tokenizer.decode(piece[:,:arg_hop])[0] # NEW
            i += hop if hop > 0 else 3000
        new_tok = [i for i in new_tok.astype(mx.int32).tolist()[0] if i < 50257]
        return self.tokenizer.decode(new_tok)[0], timestamped
```

**Comment by DiMiTriFrog** [comment]
> Would it be possible to implement support for word timestamps? And output them in .json file.
> 
> So 0_test.mp3 would produce something like this:
> 
> {"text": " he broke his ties with groups of former friends.", "segments": [{"id": 0, "seek": 0, "start": 0.0, "end": 2.12, "text": " he broke his ties with groups of former friends.", "tokens": [5036 5, 415, 6902, 702, 14039, 365, 3935, 295, 5819, 1855, 13, 50484], "temperature": 0.0, "avg_logprob": -0.2811406942514273, "compression_ratio": 0.8888888888888888, "no_speech_prob": 2.7216827424604573 e-13, "words": [{"word": " he", "start": 0.0, "end": 0.16, "probability": 0.5108894109725952}, {"word": " broke", "start": 0.16, "end": 0.42, "probability": 0.9929890632629395}, {"word": " his", "sta rt": 0.42, "end": 0.6, "probability": 0.9917784333229065}, {"word": " ties", "start": 0.6, "end": 0.88, "probability": 0.9973449110984802}, {"word": " with", "start": 0.88, "end": 1.1, "probability": 0.9941546320915222}, {"word": " groups", "start": 1.1, "end": 1.38, "probability": 0.980868399143219}, {"word": " of", "start": 1.38, "end": 1.56, "probability": 0.9978156089782715}, {"word": " form er", "start": 1.56, "end": 1.8, "probability": 0.9916045069694519}, {"word": " friends.", "start": 1.8, "end": 2.12, "probability": 0.9920713305473328}]}], "language": "en"}

How did yo do this and how did yo solve it? Could you send an example code? I'm not able to get other output than full text transcription.
